### ISSUE TITLE
roscore question~~

### ISSUE THREAD

**Issue by chbang76** [introlab/ros_for_ios#7]
We just try to connect the iPad to iPad only.
(we will not use any other computer or device.)

how to use roscore operation in your framework what is this?

**Comment by Ronan0912** [comment]
The ROS mechanism is based on a master node where client nodes can connect (it uses XMLRPC-based API). The ros client has been implemented in C++ (roscpp) and Python (rospy). The master has been implemented only in Python (rosmaster). On iOS you can develop applications in C++/Objective-C, so we have only built the roscpp client on iOS.

Currently, if you want to use ROS on several iPads, you need to run a rosmaster on a computer and set the ROS_MASTER_URI on the iPads. You will be able to have the same features as roscpp on a computer.

Ronan
